stages:
  preprocess_data:
    cmd: python src/data/make_dataset.py 'data/raw/train.csv' 'data/interim/train.pkl'
      'data/processed/target.pkl'; python src/data/make_dataset.py 'data/raw/test.csv'
      'data/interim/test.pkl' '.'
    deps:
    - data/raw
    outs:
    - data/interim
  features_data:
    cmd: python src/features/build_features.py 'data/interim/train.pkl' 'data/processed/train.pkl';
      python src/features/build_features.py 'data/interim/test.pkl' 'data/processed/test.pkl'
    deps:
    - data/interim
    outs:
    - data/processed
